feature: Disable button for empty comment field (#37)
harshmangalam/hydrogen-solidjs-client pull request #43
Opened 2022-10-03 10:03 UTC by arsen1c

Fixes issue #37 .

This commit disables the comment button if the text field is empty.

### Before
![image](https://user-images.githubusercontent.com/46086050/193551215-ecb1a323-4f2c-4caf-a6c4-03dc49d27fe7.png)

### After
![image](https://user-images.githubusercontent.com/46086050/193551274-ffd3942e-b608-48ec-ac1b-70066fbeb06e.png)

Now the comment button will only be available when some content is provided in the textarea.
![image](https://user-images.githubusercontent.com/46086050/193551404-aedfc550-cc78-4605-b1af-18ee08c5cd9b.png)

2022-10-03 13:20 UTC, harshmangalam requested changes
Please add all this changes

2022-10-03 18:12 UTC, arsen1c commented
That's a  valid point, I will add those.

2022-10-03 18:30 UTC, arsen1c reviewed
Made the necessary changes.

![image](https://user-images.githubusercontent.com/46086050/193651909-1aed5e6e-a96a-45b6-a306-00a2ced31ee0.png)

2022-10-04 02:22 UTC, harshmangalam approved these changes
Approved

2022-10-04 02:23 UTC, merged